name: master

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'

jobs:
  # First machine, runs BP tests batch 1
  integration_tests1:
    name: Instance Test 1
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.0
        run: sudo xcode-select -s /Applications/Xcode_14.0.app
      - name: Run Bluepill tests
        run: ./scripts/bluepill.sh instance_tests1
      - name: Capture xcresult files
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: xcresults-bp-tests1
          path: build/**/*.xcresult
          retention-days: 14

  # Second machine, runs BP tests batch 2
  integration_tests2:
    name: Instance Test 2
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.0
        run: sudo xcode-select -s /Applications/Xcode_14.0.app
      - name: Run Bluepill tests
        run: ./scripts/bluepill.sh instance_tests2
      - name: Capture xcresult files
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: xcresults-bp-tests2
          path: build/**/*.xcresult
          retention-days: 14

  # Third machine, runs Bluepill tests and makes release build
  build:
    name: Bluepill Test and build
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v3
      - name: Select Xcode 14.0
        run: sudo xcode-select -s /Applications/Xcode_14.0.app
      - name: Run Bluepill tests
        run: ./scripts/bluepill.sh runner_tests
      - name: Capture xcresult files
        if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: xcresults-bluepill-tests
          path: build/**/*.xcresult
          retention-days: 14
      - name: Build and Package
        run: ./scripts/bluepill.sh build
